# Generated by Django 3.1.1 on 2020-10-10 16:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 16, 38, 22, 594711, tzinfo=utc), verbose_name='date ended'),
        ),
    ]
