# Generated by Django 3.1.1 on 2020-10-10 16:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201010_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 16, 51, 38, 138528, tzinfo=utc), verbose_name='date ended'),
        ),
    ]
